SELECT DISTINCT F.CAR_ID, F.CAR_TYPE, F.TOTAL AS FEE
FROM
(
    SELECT C.CAR_ID, D.CAR_TYPE, (DAILY_FEE - ROUND(DAILY_FEE*(DISCOUNT_RATE/100))) * 30 AS TOTAL
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    JOIN CAR_RENTAL_COMPANY_CAR C ON D.CAR_TYPE = C.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상'
    AND D.CAR_TYPE IN ('세단', 'SUV')
) F
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON F.CAR_ID = H.CAR_ID
WHERE F.TOTAL BETWEEN 500000 AND 2000000
    AND F.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01'
    )
ORDER BY FEE DESC, F.CAR_TYPE, F.CAR_ID DESC
