-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (AMT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMT
FROM FOOD_ORDER O
WHERE DATE_FORMAT(PRODUCE_DATE,"%Y-%m") = '2022-05'
GROUP BY PRODUCT_ID) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID