-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, sum(PRICE)
FROM USED_GOODS_BOARD b
    JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING sum(PRICE) >= 700000
ORDER BY sum(PRICE)
;